add new benchmark for `FutureGroup`
yoshuawuyts/futures-concurrency pull request #179
Opened 2024-04-16 05:07 UTC by soooch

This benchmark aims to measure latency between futures becoming ready and the stream producing them.
The bench currently shows `FutureGroup` trailing significantly behind `FuturesUnordered` for larger test sizes.

```
future_group_poll_latency/FutureGroup/10                                                                             
                        time:   [778.96 ns 779.93 ns 780.95 ns]
                        change: [-1.0858% -0.9324% -0.7562%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 3 outliers among 100 measurements (3.00%)
  1 (1.00%) high mild
  2 (2.00%) high severe
future_group_poll_latency/FuturesUnordered/10                                                                             
                        time:   [681.78 ns 682.62 ns 683.44 ns]
                        change: [+1.8030% +1.8814% +1.9546%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 4 outliers among 100 measurements (4.00%)
  1 (1.00%) low severe
  3 (3.00%) low mild
future_group_poll_latency/FutureGroup/100                                                                             
                        time:   [13.910 µs 13.913 µs 13.915 µs]
                        change: [-1.3644% -1.2155% -1.0705%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 4 outliers among 100 measurements (4.00%)
  3 (3.00%) high mild
  1 (1.00%) high severe
future_group_poll_latency/FuturesUnordered/100                                                                             
                        time:   [3.1100 µs 3.1103 µs 3.1107 µs]
                        change: [-2.4229% -2.4009% -2.3797%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 6 outliers among 100 measurements (6.00%)
  2 (2.00%) low mild
  4 (4.00%) high mild
Benchmarking future_group_poll_latency/FutureGroup/1000: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 6.8s, enable flat sampling, or reduce sample count to 60.
future_group_poll_latency/FutureGroup/1000                                                                             
                        time:   [1.1825 ms 1.1856 ms 1.1881 ms]
                        change: [-1.3830% -0.9310% -0.5172%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 24 outliers among 100 measurements (24.00%)
  22 (22.00%) low severe
  2 (2.00%) high mild
future_group_poll_latency/FuturesUnordered/1000                                                                            
                        time:   [31.549 µs 31.555 µs 31.562 µs]
                        change: [+1.7837% +1.8228% +1.8749%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 12 outliers among 100 measurements (12.00%)
  2 (2.00%) low severe
  2 (2.00%) low mild
  3 (3.00%) high mild
  5 (5.00%) high severe
```

2024-04-16 05:17 UTC, soooch commented on benches/bench.rs
> +                ((size as f64) * MAX_READY_RATIO_PER_POLL).max(1.) as usize;
sorry these names and explanations are awkward as hell. super open to suggestions.

2024-04-16 05:18 UTC, soooch commented on benches/bench.rs
> +    fn future_group_throughput_bench(c: &mut Criterion) {
throughput is maybe not the best name for this bench?

2024-04-16 11:24 UTC, yoshuawuyts requested changes
Thanks so much for submitting this! - Despite not doing the best in these benchmarks yet, I think they're valuable because they allow us to learn where we have an opportunity to improve.

In principle I'm keen to land these; I mainly just have some concerns about the relatively high amount of outliers at the higher counts. If we can resolve that, I think we should be good!

Thank you!

2024-04-16 11:24 UTC, yoshuawuyts commented on benches/bench.rs
> +            total_runtime
It took me a second to read how this works; it would be really helpful if you can annotate how the latency is being counted here.

From what I can tell, what we're doing is taking N rounds to complete all futures in the group. We count how long it took to complete each round, and add that to a total duration. The way we mark futures as complete is by inserting one-shot channels into the futures group.

Did I get that right?

2024-04-16 11:24 UTC, yoshuawuyts commented on benches/bench.rs
> +    fn future_group_throughput_bench(c: &mut Criterion) {
Yeah, I hear you - I'm not sure what else to call it, so I think this is probably fine?

2024-04-16 11:24 UTC, yoshuawuyts commented on benches/bench.rs
> +                senders.shuffle(&mut rng);
I don't know if this ends up making a huge difference, but I am a little uncomfortable with introducing internal RNG into the benchmark. In the benchmark results for the 1000 items we're seeing 1 in 4 samples being an outlier. That means either the benchmark itself or the system it was run on is producing unreliable results.

Can we make this reordering deterministic? Can we perhaps use the current sample counter to permute the senders list?

2024-04-16 11:33 UTC, yoshuawuyts commented
@soooch By the way, I'd also be interested if you have any theories as to what might be causing this difference in latency? I know for example that in #137 we started dropping futures before we return their values, as a matter of correctness. I don't know whether `FuturesUnordered` does the same thing; but if they don't I could see that having a measurable impact on latency between futures completing and values being returned.

@soooch Also another question: it seems right now the test is hard-coded to taking 10 rounds. Have you noticed any differences if you increase or decrease the number of rounds?

2024-04-16 12:53 UTC, soooch commented on benches/bench.rs
> +            total_runtime
will get some more comments in there.

2024-04-17 17:48 UTC, yoshuawuyts commented
> my primary theory is that for each poll, all futures are iterated over regardless of whether they have been woken or not. iirc FuturesUnordered does some more complicated stuff there so it only iterates on woken futures. i think i saw an old PR on this repo that was trying to do something similar.

Hmmm, thank you for your answer - though that shouldn't be the case. We're being quite careful to only iterate over futures which are currently ready to be woken. We do iterate over all active keys, but that just walks a `BTreeSet`, which should be fairly cheap?:

https://github.com/yoshuawuyts/futures-concurrency/blob/dec5ce0c7f650aa6fccdcfe1e71147171402a5c4/src/future/future_group.rs#L363-L364

I'm quite surprised about the differences measured here; especially since on the existing benchmark we also measure time elapsed and the differences are effectively negligable. I'm hoping that by better understanding the way this benchmark is structured we can drill down further into why it performs differently for both APIs.

2024-04-17 18:02 UTC, soooch commented
> > my primary theory is that for each poll, all futures are iterated over regardless of whether they have been woken or not. iirc FuturesUnordered does some more complicated stuff there so it only iterates on woken futures. i think i saw an old PR on this repo that was trying to do something similar.
> 
> Hmmm, thank you for your answer - though that shouldn't be the case. We're being quite careful to only iterate over futures which are currently ready to be woken. We do iterate over all active keys, but that just walks a `BTreeSet`, which should be fairly cheap?:
> 
> https://github.com/yoshuawuyts/futures-concurrency/blob/dec5ce0c7f650aa6fccdcfe1e71147171402a5c4/src/future/future_group.rs#L363-L364
> 
> I'm quite surprised about the differences measured here; especially since on the existing benchmark we also measure time elapsed and the differences are effectively negligable. I'm hoping that by better understanding the way this benchmark is structured we can drill down further into why it performs differently for both APIs.

The`is_pending` and `clear_ready` are probably more expensive than the btree iteration. not sure if they’re expensive in an absolute sense though .But if it’s done for 1000 items when only a single item has woken up that should start to add up, right?

2024-04-17 21:45 UTC, soooch commented on benches/bench.rs
> +                senders.shuffle(&mut rng);
Did verify that this usage of rand is deterministic

2024-04-17 23:08 UTC, soooch commented on benches/bench.rs
> +            total_runtime
@yoshuawuyts let me know if the new docs make this more clear

2024-04-17 23:12 UTC, soooch commented on benches/bench.rs
> +                senders.shuffle(&mut rng);
also I removed the randomness from the "ready_per_round" count. That is now a parameter of the bench.

2024-04-18 01:04 UTC, soooch commented
> > > my primary theory is that for each poll, all futures are iterated over regardless of whether they have been woken or not. iirc FuturesUnordered does some more complicated stuff there so it only iterates on woken futures. i think i saw an old PR on this repo that was trying to do something similar.
> > 
> > 
> > Hmmm, thank you for your answer - though that shouldn't be the case. We're being quite careful to only iterate over futures which are currently ready to be woken. We do iterate over all active keys, but that just walks a `BTreeSet`, which should be fairly cheap?:
> > https://github.com/yoshuawuyts/futures-concurrency/blob/dec5ce0c7f650aa6fccdcfe1e71147171402a5c4/src/future/future_group.rs#L363-L364
> > 
> > I'm quite surprised about the differences measured here; especially since on the existing benchmark we also measure time elapsed and the differences are effectively negligable. I'm hoping that by better understanding the way this benchmark is structured we can drill down further into why it performs differently for both APIs.
> 
> The`is_pending` and `clear_ready` are probably about as expensive as the btree iteration. they’re not expensive in an absolute sense. But if they're done for 1000 items when only a single item has woken up that should start to add up, right?
> 
> Take a look at the `ready_to_run_queue` in `FuturesUnordered`

I think I've confirmed this theory to myself. the following change brings FutureGroup to parity with FuturesUnordered for this benchmark.

We are still more algorithmically complex than FuturesUnordered, but iter_ones on BitVec is sufficiently well optimized that we're still faster than FuturesUnordered until the test size gets to around 10000 futures.

```diff
diff --git a/src/future/future_group.rs b/src/future/future_group.rs
index bcb4fa4..45b48cf 100644
--- a/src/future/future_group.rs
+++ b/src/future/future_group.rs
@@ -1,4 +1,3 @@
-use alloc::collections::BTreeSet;
 use core::fmt::{self, Debug};
 use core::ops::{Deref, DerefMut};
 use core::pin::Pin;
@@ -65,7 +64,6 @@ pub struct FutureGroup<F> {
     futures: Slab<F>,
     wakers: WakerVec,
     states: PollVec,
-    keys: BTreeSet<usize>,
     capacity: usize,
 }
 
@@ -115,7 +113,6 @@ impl<F> FutureGroup<F> {
             futures: Slab::with_capacity(capacity),
             wakers: WakerVec::new(capacity),
             states: PollVec::new(capacity),
-            keys: BTreeSet::new(),
             capacity,
         }
     }
@@ -190,10 +187,9 @@ impl<F> FutureGroup<F> {
     /// # })
     /// ```
     pub fn remove(&mut self, key: Key) -> bool {
-        let is_present = self.keys.remove(&key.0);
+        let is_present = self.futures.try_remove(key.0).is_some();
         if is_present {
             self.states[key.0].set_none();
-            self.futures.remove(key.0);
         }
         is_present
     }
@@ -215,7 +211,7 @@ impl<F> FutureGroup<F> {
     /// # })
     /// ```
     pub fn contains_key(&mut self, key: Key) -> bool {
-        self.keys.contains(&key.0)
+        self.futures.contains(key.0)
     }
 
     /// Reserves capacity for `additional` more futures to be inserted.
@@ -270,7 +266,6 @@ impl<F: Future> FutureGroup<F> {
         }
 
         let index = self.futures.insert(future);
-        self.keys.insert(index);
 
         // Set the corresponding state
         self.states[index].set_pending();
@@ -293,7 +288,6 @@ impl<F: Future> FutureGroup<F> {
         // SAFETY: inserting a value into the futures slab does not ever move
         // any of the existing values.
         let index = unsafe { this.futures.as_mut().get_unchecked_mut() }.insert(future);
-        this.keys.insert(index);
         let key = Key(index);
 
         // If our slab allocated more space we need to
@@ -365,8 +359,8 @@ impl<F: Future> FutureGroup<F> {
         // single futures. Either to read from them or to drop them.
         let futures = unsafe { this.futures.as_mut().get_unchecked_mut() };
 
-        for index in this.keys.iter().cloned() {
-            if states[index].is_pending() && readiness.clear_ready(index) {
+        while let Some(index) = readiness.take_next_ready() {
+            if states[index].is_pending() {
                 // unlock readiness so we don't deadlock when polling
                 #[allow(clippy::drop_non_drop)]
                 drop(readiness);
@@ -398,12 +392,6 @@ impl<F: Future> FutureGroup<F> {
             }
         }
 
-        // Now that we're no longer borrowing `this.keys` we can remove
-        // the current key from the set
-        if let Poll::Ready(Some((key, _))) = ret {
-            this.keys.remove(&key.0);
-        }
-
         ret
     }
 }
diff --git a/src/utils/wakers/vec/readiness_vec.rs b/src/utils/wakers/vec/readiness_vec.rs
index d7a8640..d392c6b 100644
--- a/src/utils/wakers/vec/readiness_vec.rs
+++ b/src/utils/wakers/vec/readiness_vec.rs
@@ -65,6 +65,12 @@ impl ReadinessVec {
         self.ready_count > 0
     }
 
+    pub(crate) fn take_next_ready(&mut self) -> Option<usize> {
+        let index = self.readiness_list.iter_ones().next()?;
+        self.clear_ready(index);
+        Some(index)
+    }
+
     /// Access the parent waker.
     #[inline]
     pub(crate) fn parent_waker(&self) -> Option<&Waker> {
```

2024-04-23 01:45 UTC, soooch commented on benches/bench.rs
> +    ///   ready futures to be produced from [`FutureGroup`]'s `Stream` impl.
```suggestion
    /// - until the [`FutureGroup`] is empty, we set some fraction of the
    ///   pending futures to ready, then record how long it takes for their
    ///   outputs to be produced from [`FutureGroup`]'s `Stream` impl.
```

2024-04-23 01:48 UTC, soooch commented on benches/bench.rs
> +    /// stream.
```suggestion
    /// This benchmark measures the latency between futures becoming ready
    /// and their outputs appearing on the [`FutureGroup`] stream.
```

2024-04-23 02:32 UTC, soooch commented
> Thanks so much for submitting this! - Despite not doing the best in these benchmarks yet, I think they're valuable because they allow us to learn where we have an opportunity to improve.
> 
> In principle I'm keen to land these; I mainly just have some concerns about the relatively high amount of outliers at the higher counts. If we can resolve that, I think we should be good!
> 
> Thank you!

So it appears I have a significant number of outliers for nearly every bench included in this crate on my machine. This new benchmark is about on par with the rest.

2024-05-15 05:27 UTC, soooch commented
@yoshuawuyts this may have fallen through the cracks. I believe I've addressed your initial concerns.

2024-06-09 00:10 UTC, yoshuawuyts approved these changes
Thanks again!

2024-06-09 00:10 UTC, merged