Remove `MaybeDone` from `tuple::join`
yoshuawuyts/futures-concurrency pull request #74
Opened 2022-11-14 19:55 UTC by matheus-consoli

Remove the need for `MaybeDone` on `tuple::join` by creating for each future three fields: the Future itself; its result; its state.

I had to add a dependency on `paste` to create the `$F_fields`.

Bench:
```text
>> critcmp main patch -f tuple::join
group             main                                   patch
-----             ----                                   -----
tuple::join 10    1.00    232.6±9.13ns        ? ?/sec    1.14    266.0±3.09ns        ? ?/sec
```

2022-11-14 23:04 UTC, yoshuawuyts approved these changes
This looks great, thank you so much!

2022-11-14 23:21 UTC, yoshuawuyts requested changes
Actually, on second thought: I just noticed we have a perf regression and I think it might be because we're doing extra copies at the end. Meaning we've added extra machinery, but don't quite reap the benefits we hoped we would

I've added some in-line comments explaining what's going on. Do you think you could update it to work that way?

2022-11-14 23:21 UTC, yoshuawuyts commented on src/future/join/tuple.rs
> +                )*
We may want to create named fields here instead:

```suggestion
                futures: ($(#[pin]$F,)*),
                output: ($(MaybeUninit<$F::Output>,)*),
                state: ($(PollState,)*),
```

2022-11-14 23:21 UTC, yoshuawuyts commented on src/future/join/tuple.rs
> +                    }
The regression we're seeing is probably because of this. The main performance benefit of #22 is that we prevent an extra copy at the end. Say we have a tuple `(A, B)`, the output would always be `(A::Output, B::Output)` unless the future is cancelled.

Because we know this we can then store a field in-line of: `(MaybeUninit<A::Output>, MaybeUninit<B::Output>)`, which once we know all fields have been initialized we can just return from the future as-is. This patch unfortunately doesn't quite do that; in order to mark the fields as "initialized" here, it does a move.

That's why I'm suggesting we instead find a way to store `futures`, `output`, and `state` as separate fields of tuples - and find a way to index into them.

2022-11-14 23:21 UTC, yoshuawuyts commented on src/future/join/tuple.rs
> +                        all_done &= this.[<$F _state>].is_done();
Oof haha, I forgot we had this. We should probably initialize a counter set to `len: utils::tuple_len!()` inside the struct, and then with each completed future count down. That will also set us up to enable https://github.com/yoshuawuyts/futures-concurrency/issues/21 to work, since we'll want to stop calling all wakers on each iteration anyway. But that doesn't have to be inside this patch.

2022-11-16 00:22 UTC, matheus-consoli commented
I've reworked this a bit:
- no `paste` dep
- no tuple copy from `(MaybeUninit<A>,..)` to `(A,)`

but it got somewhat worst hahaha

I'll try to figure out a better way to impl this later, but let me know if you have any ideas :)

```text
>> critcmp main patch -f tuple::join
group             main                                   patch
-----             ----                                   -----
tuple::join 10    1.00    231.6±0.73ns        ? ?/sec    1.19    275.7±1.31ns        ? ?/sec
```

<details>
  <summary>for reference, the macro is desugaring `Join3<A, B, C>` as follows:</summary>

```rust
#[pin_project]
#[must_use = "futures do nothing unless you `.await` or poll them"]
#[allow(non_snake_case)]
pub struct Join3<A: Future, B: Future, C: Future> {
    len: u32,
    #[pin] A: A,
    #[pin] B: B,
    #[pin] C: C,
    outputs: (
        MaybeUninit<A::Output>,
        MaybeUninit<B::Output>,
        MaybeUninit<C::Output>,
    ),
    states: PollStates,
}

impl<A: Future, B: Future, C: Future> Future for Join3<A, B, C> {
    type Output = (A::Output, B::Output, C::Output);
    fn poll(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {
        let mut this = self.project();
        if this.states[0].is_pending() {
            if let Poll::Ready(out) = this.A.poll(cx) {
                this.outputs.0 = MaybeUninit::new(out);
                this.states[0] = PollState::Done;
                *this.len -= 1;
            }
        };
        if this.states[1].is_pending() {
            if let Poll::Ready(out) = this.B.poll(cx) {
                this.outputs.1 = MaybeUninit::new(out);
                this.states[1] = PollState::Done;
                *this.len -= 1;
            }
        };
        if this.states[2].is_pending() {
            if let Poll::Ready(out) = this.C.poll(cx) {
                this.outputs.2 = MaybeUninit::new(out);
                this.states[2] = PollState::Done;
                *this.len -= 1;
            }
        };
        if *this.len <= 0 {
            let out = unsafe {
                (this.outputs as *const _ as *const (A::Output, B::Output, C::Output)).read()
            };
            Poll::Ready(out)
        } else {
            Poll::Pending
        }
    }
}
```
</details>

2022-11-16 17:45 UTC, yoshuawuyts commented on src/future/join/tuple.rs
> +}
Can you explain how this works? I'm not sure I completely follow, heh.

I was somewhat hoping we could create something like [`gen_conditions!`](https://github.com/yoshuawuyts/futures-concurrency/blob/main/src/utils/tuple.rs#L38-L56) which can be reused between implementations. Would that be possible?

2022-11-16 17:45 UTC, yoshuawuyts commented on src/future/join/tuple.rs
> +            $(#[pin] $F: $F,)*
Would it be possible to instead do:

```suggestion
            tuple: ($(#[pin] $F: $F,)*),
```

That way we can move the tuple fields into here basically in-place.

2022-11-16 19:10 UTC, matheus-consoli commented on src/future/join/tuple.rs
> +}
sure!

The idea is quite simple: to unroll a for-loop through all tuple elements.

But this is kinda a mess, because accessing tuples on macros is messy.

My first attempt was to create something akin to `gen_conditions`, a `for i in 0..LEN` calling a macro for each index accessing the tuple element. But we cannot `$tuple.$i` because `$i` is a variable, not a literal, and this would translate to `tuple.i`.

So I tried to inline/unroll the for.

The way this goes is by taking all type parameters the JoinN has, "poping" the first element (`$fut`), and generating the poll for that future (`maybe_poll`) - along the way, we have the "iteration index" as literal. Next, we call the next index with the rest of the generics. Once the list is empty, the macro will match the `(@inner $ignore:literal, $len:ident, $this:ident, $cx:ident, ())` and generate nothing, stopping the recursion.

I can elaborate on it better later, documenting it on code.

We can use `trace_macros` to see how this expand:
```rust
note: trace_macro
   --> src/future/join/tuple.rs:163:1
    |
163 | impl_join_tuple! { Join3 A B C }
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: expanding `poll_all_pending! { LEN, this, cx, A, B, C, }`
    = note: to `poll_all_pending! (@ inner 0, LEN, this, cx, (A, B, C,)) ;`
    = note: expanding `poll_all_pending! { @ inner 0, LEN, this, cx, (A, B, C,) }`
    = note: to `maybe_poll! (0, LEN, this, A, cx) ; poll_all_pending!
            (@ inner 1, LEN, this, cx, (B, C,)) ;`
    = note: expanding `maybe_poll! { 0, LEN, this, A, cx }`
    = note: to `if this.states [0].is_pending()
            {
                if let Poll :: Ready(out) = this.A.poll(cx)
                {
                    this.outputs.0 = MaybeUninit :: new(out) ; this.states [0] = PollState
                    :: Done ; * this.len -= 1 ;
                }
            }`
    = note: expanding `poll_all_pending! { @ inner 1, LEN, this, cx, (B, C,) }`
    = note: to `maybe_poll! (1, LEN, this, B, cx) ; poll_all_pending!
            (@ inner 2, LEN, this, cx, (C,)) ;`
    = note: expanding `maybe_poll! { 1, LEN, this, B, cx }`
    = note: to `if this.states [1].is_pending()
            {
                if let Poll :: Ready(out) = this.B.poll(cx)
                {
                    this.outputs.1 = MaybeUninit :: new(out) ; this.states [1] = PollState
                    :: Done ; * this.len -= 1 ;
                }
            }`
    = note: expanding `poll_all_pending! { @ inner 2, LEN, this, cx, (C,) }`
    = note: to `maybe_poll! (2, LEN, this, C, cx) ; poll_all_pending!
            (@ inner 3, LEN, this, cx, ()) ;`
    = note: expanding `maybe_poll! { 2, LEN, this, C, cx }`
    = note: to `if this.states [2].is_pending()
            {
                if let Poll :: Ready(out) = this.C.poll(cx)
                {
                    this.outputs.2 = MaybeUninit :: new(out) ; this.states [2] = PollState
                    :: Done ; * this.len -= 1 ;
                }
            }`
    = note: expanding `poll_all_pending! { @ inner 3, LEN, this, cx, () }`
    = note: to ``
```

2022-11-16 19:10 UTC, matheus-consoli commented on src/future/join/tuple.rs
> +            $(#[pin] $F: $F,)*
I'm currently trying to figure out how to do this!

`tuple: ($(#[pin] $F: $F,)*)` doesn't work because `pin_project` doesn't support pinning this way, like `(#[pin] T, #[pin] S)`

2022-11-17 02:44 UTC, matheus-consoli commented on src/future/join/tuple.rs
> +            $(#[pin] $F: $F,)*
@yoshuawuyts, I got something!

It's on a second branch, [here](https://github.com/yoshuawuyts/futures-concurrency/compare/main...matheus-consoli:futures-concurrency:remove-maybedone-from-join-tuple-take2).

I took some inspiration from #84 to use the pinned futures inside a tuple(struct), and it kinda works.

We have some performance gain, but it's kinda negligible :disappointed: (especially because of the macro-heavy impl orientation)

```text
>> critcmp main patch -f tuple::join
group             main                                   patch
-----             ----                                   -----
tuple::join 10    1.03    239.3±1.06ns        ? ?/sec    1.00    231.3±0.79ns        ? ?/sec
```

2022-11-17 11:12 UTC, yoshuawuyts commented on src/future/join/tuple.rs
> +            $(#[pin] $F: $F,)*
Oh yeah, I like the intermediate struct approach!

The reason why there's a small perf cost might be because you're using `ptr::read` there which [ends up doing an extra copy]((https://doc.rust-lang.org/src/core/ptr/mod.rs.html#1117))? Instead I think if it's at all possible it might be worth attempting to perform a direct transmute? This might require adding a `#[repr(transparent)]` to the `Futures` struct so that the layout is guaranteed to be the same as the tuples it stores?

2022-11-17 12:19 UTC, yoshuawuyts commented on src/future/join/tuple.rs
> +}
I seee, that makes sense! Thank you for explaining. I think something which maybe threw me off a bit is the fact that the arm which matches on "tuples of length 12" is marked as `@inner 1`, and the arm which matches on "tuples of length 1" is marked as `@inner 11`. If the count could match the number of tuples it operates on it might be easier to reason about perhaps?

Now that you've explained it I'm on board with this approach! - If we could figure out a way to make this reusable that'd still be nice, but we don't have to do that in this patch.

2022-11-17 17:42 UTC, matheus-consoli commented on src/future/join/tuple.rs
> +            $(#[pin] $F: $F,)*
oh, I don't think `#[repr(transparent)] Futures` is possible, `transparent` only allows one field to have a non-zero size, the `Futures` have many.

2022-11-17 17:46 UTC, matheus-consoli commented on src/future/join/tuple.rs
> +            $(#[pin] $F: $F,)*
I'm trying to `transmute`, but maybe I have found a limitation (?)

I can transmute from `(MaybeUninit<ConcreteTypeA>, MaybeUninit<ConcreteTypeB>)` to `(ConcreteTypeA, ConcreteTypeB)`, but I can't to the same from `(MaybeUninit<GenericTypeA>, MaybeUninit<GenericTypeB>)`, [play](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=e948fe4a441734c81c5ce7b35290a23b)

I'll try again after lunch

2022-11-17 18:31 UTC, yoshuawuyts commented on src/future/join/tuple.rs
> +            $(#[pin] $F: $F,)*
> oh, I don't think `#[repr(transparent)] Futures` is possible, `transparent` only allows one field to have a non-zero size, the `Futures` have many.

oof, TIL :')

2022-11-17 23:07 UTC, matheus-consoli commented on src/future/join/tuple.rs
> +            $(#[pin] $F: $F,)*
oook, it seems to me that we cannot transmute `(MaybeUninit<T>, MaybeUninit<U>)` to `(T, U)`.

I'm not sure why, but I guess it's the same underlying problem from rust-lang/rust#61956, so casting the tuples appears to be the best option so far

2022-11-17 23:24 UTC, matheus-consoli commented on src/future/join/tuple.rs
> +}
hm, but the "tuples of length 12" are not marked as `@inner 1`, nor the "tuples of length 1" are marked as `@inner 11`

it recursively unrolls to the size of the tuple, starting from 0 to the size - 1

assume we can read `@inner` as `@access_index_on_tuple` and we're unrolling a `(A, B, C)`

the macro goes as:
> `poll_all_pending!(tuple, (A, B, C))`
> `@access_index 0 on tuple $tuple remaining (A, B, C)`
> `$tuple.0` && `@access_index 1 on tuple $tuple remaining (B, C)`
> `$tuple.1` && `@access_index 2 on tuple $tuple remaining (C,)`
> `$tuple.2` && `@access_index 3 on tuple $tuple remaining ()`
> oh, remaining is empty, nothing left, stop here (aka `(@inner $ignore:literal, $len:ident, $this:ident, $cx:ident, ()) => { };
`

does that make sense?

2022-11-18 15:57 UTC, yoshuawuyts commented on src/future/join/tuple.rs
> +}
It does, thank you!

2022-11-18 16:18 UTC, yoshuawuyts approved these changes
I've just approved https://github.com/yoshuawuyts/futures-concurrency/pull/96. It seems this PR has merge conflicts anyway; if those can be resolved I think this should be good to go as well.

Either as part of this PR, or as part of a follow-up PR we should switch this implementation over to using [`tuple_for_each!`](https://github.com/yoshuawuyts/futures-concurrency/pull/96/files#diff-10eb736ee20e16b51fcc09b522c927cf43cbf8d4a5e55bfe40942b3718eddb64) as well, so the underlying implementation can be shared between all tuples.

2022-11-18 17:26 UTC, poliorcetics commented on src/future/join/tuple.rs
> +            $(#[pin] $F: $F,)*
Transmuting is not what you want here I think ?

```rust
let t = (MaybeUninit::<usize>::new(42), MaybeUninit::<u8>::new(12)); // source, can come from anywhere

/* ... */

// Where you wanted to transmute:
let (a, b) = t;
(a.assume_init(), b.assume_init())
```

This can be macro-ified using `$F` as the variable name: it won't even shadow the type names because that's two different namespaces (`let usize: usize = 4_usize;` is valid)

2022-11-18 17:27 UTC, poliorcetics commented on src/future/join/tuple.rs
> +            $(#[pin] $F: $F,)*
Assuming the `t` is owned, this should not do any copy anywhere

2022-11-18 23:47 UTC, matheus-consoli commented on src/future/join/tuple.rs
> +            $(#[pin] $F: $F,)*
ohh, thank you for pointing it out! I'll try that

2022-11-19 17:39 UTC, poliorcetics commented on src/future/join/tuple.rs
> +                    states: PollStates::new(LEN as usize),
PollArray is usable here

2022-11-20 03:11 UTC, matheus-consoli commented
I'm closing this PR in favor of #103 

I opted to start from a clean new branch instead of dealing with this branch conflicts :sweat_smile: 

Thank you all!

2022-11-20 03:11 UTC, closed without merging